BackendFinalProjectEduHome/Areas/Admin/Controllers/EventController.cs
using BackendFinalProjectEduHome.Areas.Admin.Data;
using BackendFinalProjectEduHome.Areas.Admin.ViewModels;
using BackendFinalProjectEduHome.DAL;
using BackendFinalProjectEduHome.DAL.Entity;
using BackendFinalProjectEduHome.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.Internal;
using Microsoft.Extensions.Logging;

namespace BackendFinalProjectEduHome.Areas.Admin.Controllers
{
    public class EventController : BaseController
    {
        private readonly EduHomeDbContext _dbContext;

        public EventController(EduHomeDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Event> events = await _dbContext.Events
                .Include(e => e.EventSpeakers).ThenInclude(es => es.Speaker)
                .Where(e => !e.IsDeleted)
                .OrderByDescending(e => e.Id)
                .ToListAsync();

            return View(events);
        }

        public async Task<IActionResult> Create()
        {
            var speakers = await _dbContext.Speakers.ToListAsync();

            var eventSpeakersSelectList = new List<SelectListItem>();

            speakers.ForEach(c => eventSpeakersSelectList
            .Add(new SelectListItem(c.Firstname + " " + c.Lastname, c.Id.ToString())));

            var model = new EventCreateViewModel
            {
                Speakers = eventSpeakersSelectList
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EventCreateViewModel model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.StartDate.ToString("yyyy") != model.EndDate.ToString("yyyy")
                || model.StartDate.ToString("MM") != model.EndDate.ToString("MM")
                || model.StartDate.ToString("dd") != model.EndDate.ToString("dd"))
            {
                ModelState.AddModelError("", "Start Date and End Date must be same day");
                return View(model);
            }

            if (!model.Image.IsImage())
            {
                ModelState.AddModelError("", "Must be selected image");
                return View(model);
            }

            if (!model.Image.IsAllowedSize(7))
            {
                ModelState.AddModelError("", "Image size can be max 7 mb");
                return View(model);
            }

            var unicalName = await model.Image.Generatefile(Constants.EventPath);

            var events = new Event
            {
                Title = model.Title,
                Description = model.Description,
                ImageUrl = unicalName,
                Address = model.Address,
                EndDate = model.EndDate,
                StartDate = model.StartDate,
            };

            List<EventSpeaker> eventSpeakers = new List<EventSpeaker>();

            var speakers = await _dbContext.Speakers.Where(s => !s.IsDeleted).ToListAsync();

            var eventSpeakersSelectList = new List<SelectListItem>();

           
            speakers.ForEach(c => eventSpeakersSelectList
            .Add(new SelectListItem(c.Firstname + " " + c.Lastname, c.Id.ToString())));

            var viewModel = new EventCreateViewModel
            {

                Speakers=eventSpeakersSelectList,
                Image=model.Image
            };

            foreach (int speakerId in model.SpeakerIds)
            {
                if (!await _dbContext.Speakers.AnyAsync(s => s.Id == speakerId))
                {
                    ModelState.AddModelError("", "Incorect Speaker");
                    return View(viewModel);
                }

                eventSpeakers.Add(new EventSpeaker
                {
                    SpeakerId = speakerId,
                });

            }

            events.EventSpeakers = eventSpeakers;
            model.Speakers = eventSpeakersSelectList;

            await _dbContext.Events.AddAsync(events);
            await _dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Update(int? id)
        {
            if (id is null) return BadRequest();

            var dbEvent = await _dbContext.Events
                .Where(e => !e.IsDeleted && e.Id == id)
                .Include(e => e.EventSpeakers).ThenInclude(es => es.Speaker)
                
                .FirstOrDefaultAsync();

            if (dbEvent is null) return NotFound();

            var speakers = await _dbContext.Speakers.Where(s => !s.IsDeleted).ToListAsync();

            var eventSpeakersSelectList = new List<SelectListItem>();

            speakers.ForEach(c => eventSpeakersSelectList
            .Add(new SelectListItem(c.Firstname + " " + c.Lastname, c.Id.ToString())));

            List<EventSpeaker> eventSpeakers = new List<EventSpeaker>();

            foreach (EventSpeaker eventSpeaker in dbEvent.EventSpeakers)
            {
                if (!await _dbContext.Speakers.AnyAsync(s => s.Id == eventSpeaker.SpeakerId))
                {
                    ModelState.AddModelError("", "Incorect Speaker Id");
                    return View();
                }

                eventSpeakers.Add(new EventSpeaker
                {
                    SpeakerId = eventSpeaker.SpeakerId
                });
            }

            var eventViewModel = new EventUpdateViewModel
            {
                Id = dbEvent.Id,
                StartDate = dbEvent.StartDate,
                EndDate = dbEvent.EndDate,
                Title = dbEvent.Title,
                Description = dbEvent.Description,
                ImageUrl = dbEvent.ImageUrl,
                Address = dbEvent.Address,
                Speakers = eventSpeakersSelectList,
                SpeakerIds = eventSpeakers.Select(s => s.SpeakerId).ToList()
            };

            return View(eventViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int? id, EventUpdateViewModel model)
        {

            if (id is null) return BadRequest();

            var dbEvent = await _dbContext.Events
                .Include(e => e.EventSpeakers).ThenInclude(es => es.Speaker)
                .Where(e => !e.IsDeleted && e.Id == id)
                .FirstOrDefaultAsync();
            var eventSpeakersSelectList = new List<SelectListItem>();

            var speakers = await _dbContext.Speakers.Where(s => !s.IsDeleted).ToListAsync();

            var viewModel = new EventUpdateViewModel
            {
                ImageUrl = dbEvent.ImageUrl,
                Speakers = eventSpeakersSelectList,

            };
            speakers.ForEach(e => eventSpeakersSelectList
            .Add(new SelectListItem(e.Firstname+" "+e.Lastname, e.Id.ToString())));

            if (dbEvent is null) return NotFound();

            if (!ModelState.IsValid) return View(viewModel);            

            if (model.StartDate.ToString("yyyy") != model.EndDate.ToString("yyyy")
                || model.StartDate.ToString("MM") != model.EndDate.ToString("MM")
                || model.StartDate.ToString("dd") != model.EndDate.ToString("dd"))
            {
                ModelState.AddModelError("", "Start Date and End Date must be same day");
                return View(viewModel);
            }

            if (model.SpeakerIds.Count > 0)
            {
                foreach (int speakerId in model.SpeakerIds)
                {
                    if (!await _dbContext.Speakers.AnyAsync(c => c.Id == speakerId))
                    {
                        ModelState.AddModelError("", "Has been selected incorrect speaker.");
                        return View(viewModel);
                    }
                }

                _dbContext.EventSpeakers.RemoveRange(dbEvent.EventSpeakers);

                List<EventSpeaker> eventSpeakers = new List<EventSpeaker>();
                foreach (var item in model.SpeakerIds)
                {
                    EventSpeaker eventSpeaker = new EventSpeaker
                    {
                        SpeakerId = item
                    };

                    eventSpeakers.Add(eventSpeaker);
                }

                dbEvent.EventSpeakers = eventSpeakers;
            }
            else
            {
                ModelState.AddModelError("", "Select minimum 1 speaker");
                return View(viewModel);
            }

            if (model.Image != null)
            {
                if (!model.Image.IsImage())
                {
                    ModelState.AddModelError("", "Must be selected image");
                    return View(viewModel);
                }

                if (!model.Image.IsAllowedSize(7))
                {
                    ModelState.AddModelError("", "Image size can be max 7 mb");
                    return View(viewModel);
                }

                if (dbEvent.ImageUrl is null) return NotFound();
               

                var eventImagePath = Path.Combine(Constants.RootPath, "assets", "img", "event", dbEvent.ImageUrl);

                if (System.IO.File.Exists(eventImagePath))
                    System.IO.File.Delete(eventImagePath);

                var unicalName = await model.Image.Generatefile(Constants.EventPath);
                dbEvent.ImageUrl = unicalName;
            }

            dbEvent.StartDate = model.StartDate;
            dbEvent.EndDate = model.EndDate;
            dbEvent.Description = model.Description;
            dbEvent.Address = model.Address;
            dbEvent.Title = model.Title;

            await _dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Details(int? id)

BackendFinalProjectEduHome/Controllers/EventController.cs
using BackendFinalProjectEduHome.DAL;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace BackendFinalProjectEduHome.Controllers
{
    public class EventController : Controller
    {
        private readonly EduHomeDbContext _dbContext;

        public EventController(EduHomeDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public async Task<IActionResult> Index()
        {
            var events = await _dbContext.Events.Where(e => !e.IsDeleted).ToListAsync();
            return View(events);
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id is null) return NotFound();
            var eventt = await _dbContext.Events.Where(c => !c.IsDeleted && c.Id == id).Include(e => e.EventSpeakers).ThenInclude(e => e.Speaker).FirstOrDefaultAsync();
            if (eventt is null) return NotFound();


            return View(eventt);
        }
    }
}

BackendFinalProjectEduHome/ViewComponents/BlogSideBarViewComponent.cs
using BackendFinalProjectEduHome.DAL;
using BackendFinalProjectEduHome.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;

namespace BackendFinalProjectEduHome.ViewComponents
{
    public class BlogSideBarViewComponent : ViewComponent
    {
        private readonly EduHomeDbContext _dbContext;

        public BlogSideBarViewComponent(EduHomeDbContext dbContext)
        {
            _dbContext = dbContext;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var categories = await _dbContext.Categories.Where(c => !c.IsDeleted)
                .Include(c => c.Courses)
                .ToListAsync();
            var blogs = await _dbContext.Blogs
                .Where(b => !b.IsDeleted)
                .Take(3)
                .OrderByDescending(b => b.Id)
                .ToListAsync();

            var model = new BlogSideBarViewModel
            {
                Blogs = blogs,
                Categories = categories
            };
            return View(model);
        }
    }
}

BackendFinalProjectEduHome/Views/Event/Details.cshtml
@{
    Event eventt = Model;
}
<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>event / details</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Event Details Start -->
<div class="event-details-area blog-area pt-150 pb-140">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div class="event-details">
                    <div class="event-details-img">
                        <img src="~/assets/img/event/@eventt.ImageUrl" style="width:687px; height:320px;" alt="event-details">
                        <div class="event-date" style="width:82px; height:86px;">
                            <h3>@eventt.StartDate.ToString("MMM dd")</h3>
                        </div>
                    </div>
                    <div class="event-details-content">
                        <h2>@eventt.Title</h2>
                        <ul>
                            <li><span>time : </span>@eventt.StartDate.ToString("hh:mm tt") - @eventt.EndDate.ToString("hh:mm tt")</li>
                            <li><span>venue : </span>@eventt.Address</li>
                        </ul>
                        <p>@eventt.Description</p>


                        <div class="speakers-area fix">
                            <h4>speakers</h4>
                            @foreach (var item in eventt.EventSpeakers)
                            {
                                <div class="single-speaker">
                                    <div class="speaker-img">
                                        <img src="~/assets/img/speaker/@item.Speaker.ImageUrl" alt="speaker">
                                    </div>
                                    <div class="speaker-name">
                                        <h5>@(item.Speaker.Firstname + " " + item.Speaker.Lastname)</h5>
                                        <p>@item.Speaker.Position, @item.Speaker.Company </p>
                                    </div>
                                </div>
                            }

                        </div>
                    </div>
                    <div class="reply-area">
                        <h3>LEAVE A REPLY</h3>
                        <p>I must explain to you how all this a mistaken idea of ncing great explorer of the rut<br> the is lder of human happinescias unde omnis iste natus error sit volptatem </p>
                        <form id="contact-form" action="http://demo.devitems.com/eduhome/mail.php" method="post">
                            <div class="row">
                                <div class="col-md-12">
                                    <p>Name</p>
                                    <input type="text" name="name" id="name">
                                </div>
                                <div class="col-md-12">
                                    <p>Email</p>
                                    <input type="text" name="email" id="email">
                                </div>
                                <div class="col-md-12">
                                    <p>Subject</p>
                                    <input type="text" name="subject" id="subject">
                                    <p>Massage</p>
                                    <textarea name="message" id="message" cols="15" rows="10"></textarea>
                                </div>
                            </div>
                            <a class="reply-btn" href="#" data-text="send"><span>send message</span></a>
                            <p class="form-messege"></p>
                        </form>
                    </div>
                </div>
            </div>
            @await Component.InvokeAsync("BlogSideBar")
        </div>
    </div>
</div>

BackendFinalProjectEduHome/Views/Event/Index.cshtml
@{
    List<Event> events = Model;
}
<!-- Banner Area Start -->
<div class="banner-area-wrapper">
    <div class="banner-area text-center">
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <div class="banner-content-wrapper">
                        <div class="banner-content">
                            <h2>event</h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Banner Area End -->
<!-- Event Start -->
<div class="event-area three text-center pt-150 pb-150">
    <div class="container">
        <div class="row">
            @foreach (var eventt in events)
            {
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="single-event mb-60">
                        <div class="event-img">
                            <a asp-controller="event" asp-action="details" asp-route-id="@eventt.Id">
                                <img src="~/assets/img/event/@eventt.ImageUrl" style="width370px;height:250px;" alt="event">
                                <div class="course-hover">
                                    <i class="fa fa-link"></i>
                                </div>
                            </a>
                            <div class="event-date">
                                <h3>@eventt.StartDate.ToString("MMM dd")</h3>
                            </div>
                        </div>
                        <div class="event-content text-left">
                            <h4><a asp-controller="event" asp-action="details" asp-route-id="@eventt.Id">@eventt.Title</a></h4>
                            <ul>
                                <li><span>time:</span> @eventt.StartDate.ToString("h:mm tt") - @eventt.EndDate.ToString("h:mm tt")</li>
                                <li><span>venue</span> @eventt.Address</li>
                            </ul>
                            <div class="event-content-right">
                                <a class="default-btn" asp-controller="event" asp-action="details" asp-route-id="@eventt.Id">join now</a>
                            </div>
                        </div>
                    </div>
                </div>
            }

        </div>
    </div>
</div>